name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            file_name: certifaction
            artifact_name: certifaction
          - os: darwin
            arch: arm64
            file_name: certifaction
            artifact_name: certifaction
          - os: windows
            arch: amd64
            file_name: certifaction.exe
            artifact_name: certifaction
          - os: windows
            arch: arm64
            file_name: certifaction.exe
            artifact_name: certifaction
          - os: linux
            arch: amd64
            file_name: certifaction
            artifact_name: certifaction
          - os: linux
            arch: arm64
            file_name: certifaction
            artifact_name: certifaction
          - os: freebsd
            arch: amd64
            file_name: certifaction
            artifact_name: certifaction
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        env:
          RUNNER_TEMP: /tmp
        with:
          go-version: 1.22

      - name: Create/Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.os }}-${{ matrix.arch}}

      - name: Run Build
        run: make build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ matrix.file_name }}
          retention-days: 7

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2